spl: SPL_ATF depends on SPL_LOAD_FIT
SPL_ATF needs a fit image, therefore the SPL must be able to parse that
image. We automatically select the small implementation if the full one
is not enabled.

This also fixes the following build error if SPL_ATF is enabled and
SPL_LOAD_FIT is not enabled:
  common/spl/spl.c: In function ‘board_init_r’:
  common/spl/spl.c:689:27: error: ‘struct spl_image_info’ has no member named ‘fdt_addr’; did you mean ‘load_addr’?

Signed-off-by: Michael Walle <michael@walle.cc>